[2023-12-05T21:47:01.814+0100] {processor.py:157} INFO - Started process (PID=31792) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:47:01.824+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:47:01.831+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:47:01.829+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:47:06.671+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:47:06.669+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:47:09.638+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:47:09.536+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:47:09.675+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:47:11.127+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:47:11.125+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:47:11.478+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:47:11.476+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:47:12.131+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:47:11.877+0100] {dagbag.py:644} ERROR - Failed to write serialized DAG: /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 633, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/models/serialized_dag.py", line 147, in write_dag
    if session.scalar(
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1742, in scalar
    return self.execute(
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1711, in execute
    conn = self._connection_for_bind(bind)
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(pipeline_mssql) already exists.

[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, data_compressed, last_updated, dag_hash, processor_subdir) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, %(data)s, %(data_compressed)s, %(last_updated)s, %(dag_hash)s, %(processor_subdir)s)]
[parameters: {'dag_id': 'pipeline_mssql', 'fileloc': '/mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py', 'fileloc_hash': 49416720035252669, 'data': '{"__version": 1, "dag": {"default_args": {"__var": {"owner": "nherm", "start_date": {"__var": 1701820800.0, "__type": "datetime"}, "retries": 1, "ret ... (10226 characters truncated) ... "pipeline_xls_xlsxcsv", "target": "pipeline_mssql", "dependency_type": "sensor", "dependency_id": "pipeline_etl_xls_xlsxcsv_sensor"}], "params": {}}}', 'data_compressed': None, 'last_updated': datetime.datetime(2023, 12, 5, 20, 47, 10, 189174, tzinfo=Timezone('UTC')), 'dag_hash': '4afd834c8eaa72cf80e1ce13b6c36110', 'processor_subdir': None}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
[2023-12-05T21:47:12.135+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:47:12.134+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:47:12.140+0100] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 857, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/dag_processing/processor.py", line 893, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 654, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 668, in _sync_to_db
    DAG.bulk_write_to_db(dags.values(), processor_subdir=processor_subdir, session=session)
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/models/dag.py", line 2953, in bulk_write_to_db
    orm_dags: list[DagModel] = session.scalars(query).unique().all()
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1771, in scalars
    return self.execute(
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1711, in execute
    conn = self._connection_for_bind(bind)
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "serialized_dag_pkey"
DETAIL:  Key (dag_id)=(pipeline_mssql) already exists.

[SQL: INSERT INTO serialized_dag (dag_id, fileloc, fileloc_hash, data, data_compressed, last_updated, dag_hash, processor_subdir) VALUES (%(dag_id)s, %(fileloc)s, %(fileloc_hash)s, %(data)s, %(data_compressed)s, %(last_updated)s, %(dag_hash)s, %(processor_subdir)s)]
[parameters: {'dag_id': 'pipeline_mssql', 'fileloc': '/mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py', 'fileloc_hash': 49416720035252669, 'data': '{"__version": 1, "dag": {"default_args": {"__var": {"owner": "nherm", "start_date": {"__var": 1701820800.0, "__type": "datetime"}, "retries": 1, "ret ... (10226 characters truncated) ... "pipeline_xls_xlsxcsv", "target": "pipeline_mssql", "dependency_type": "sensor", "dependency_id": "pipeline_etl_xls_xlsxcsv_sensor"}], "params": {}}}', 'data_compressed': None, 'last_updated': datetime.datetime(2023, 12, 5, 20, 47, 10, 189174, tzinfo=Timezone('UTC')), 'dag_hash': '4afd834c8eaa72cf80e1ce13b6c36110', 'processor_subdir': None}]
(Background on this error at: https://sqlalche.me/e/14/gkpj) (Background on this error at: https://sqlalche.me/e/14/7s2a)
[2023-12-05T21:47:43.111+0100] {processor.py:157} INFO - Started process (PID=31874) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:47:43.123+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:47:43.132+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:47:43.129+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:47:46.857+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:47:46.856+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:47:48.522+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:47:48.513+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:47:48.547+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:47:50.114+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:47:50.113+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:47:50.392+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:47:50.387+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:47:50.629+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 7.571 seconds
[2023-12-05T21:48:22.392+0100] {processor.py:157} INFO - Started process (PID=31956) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:48:22.403+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:48:22.413+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:48:22.410+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:48:26.601+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:48:26.600+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:48:28.357+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:48:28.349+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:48:28.390+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:48:28.805+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:48:28.804+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:48:29.020+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:48:29.019+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:48:29.143+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 6.801 seconds
[2023-12-05T21:49:01.029+0100] {processor.py:157} INFO - Started process (PID=32057) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:49:01.043+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:49:01.051+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:49:01.048+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:49:05.112+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:49:05.111+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:49:07.043+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:49:07.035+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:49:07.069+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:49:08.311+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:49:08.310+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:49:08.482+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:49:08.481+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:49:08.636+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 7.668 seconds
[2023-12-05T21:49:45.698+0100] {processor.py:157} INFO - Started process (PID=32201) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:49:45.714+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:49:45.778+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:49:45.721+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:49:56.605+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:49:56.603+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:49:59.666+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:49:59.654+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:49:59.701+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:50:01.328+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:50:01.326+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:50:01.845+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:50:01.843+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:50:02.295+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 16.775 seconds
[2023-12-05T21:50:34.103+0100] {processor.py:157} INFO - Started process (PID=32266) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:50:34.127+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:50:34.184+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:50:34.174+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:50:45.186+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:50:45.185+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:50:49.583+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:50:49.571+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:50:49.620+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:50:51.685+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:50:51.683+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:50:51.968+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:50:51.967+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:50:52.499+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 18.765 seconds
[2023-12-05T21:51:26.427+0100] {processor.py:157} INFO - Started process (PID=32336) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:51:26.452+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:51:26.462+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:51:26.458+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:51:31.037+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:51:31.036+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:51:33.533+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:51:33.520+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:51:33.568+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:51:34.058+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:51:34.057+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:51:34.332+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:51:34.330+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:51:34.573+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 8.220 seconds
[2023-12-05T21:52:06.625+0100] {processor.py:157} INFO - Started process (PID=32401) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:52:06.678+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:52:06.689+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:52:06.685+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:52:14.492+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:52:14.488+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:52:20.064+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:52:20.044+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:52:20.185+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:52:24.558+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:52:24.556+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:52:24.908+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:52:24.906+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:52:25.241+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 18.741 seconds
[2023-12-05T21:52:56.900+0100] {processor.py:157} INFO - Started process (PID=32480) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:52:56.918+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:52:56.930+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:52:56.924+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:53:02.288+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:53:02.285+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:53:05.085+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:53:05.067+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:53:05.133+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:53:06.353+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:53:06.345+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:53:07.142+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:53:07.140+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:53:07.600+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 10.807 seconds
[2023-12-05T21:53:44.787+0100] {processor.py:157} INFO - Started process (PID=32546) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:53:44.835+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:53:44.852+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:53:44.848+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:53:50.099+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:53:50.097+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:53:52.918+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:53:52.901+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:53:52.961+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:53:55.479+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:53:55.477+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:53:55.822+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:53:55.821+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:53:56.032+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 11.399 seconds
[2023-12-05T21:54:27.787+0100] {processor.py:157} INFO - Started process (PID=32606) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:54:27.809+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:54:27.822+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:54:27.816+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:54:30.003+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:54:30.002+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:54:31.987+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:54:31.974+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:54:32.013+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:54:32.420+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:54:32.418+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:54:32.691+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:54:32.690+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:54:32.861+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 5.170 seconds
[2023-12-05T21:55:03.290+0100] {processor.py:157} INFO - Started process (PID=32662) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:55:03.299+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:55:03.306+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:55:03.303+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:55:05.031+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:55:05.030+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:55:06.272+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:55:06.263+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:55:06.297+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:55:07.287+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:55:07.286+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:55:07.448+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:55:07.447+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:55:07.579+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.329 seconds
[2023-12-05T21:55:37.824+0100] {processor.py:157} INFO - Started process (PID=32723) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:55:37.833+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:55:37.839+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:55:37.837+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:55:39.430+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:55:39.429+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:55:40.732+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:55:40.724+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:55:40.758+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:55:41.047+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:55:41.047+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:55:41.220+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:55:41.219+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:55:41.336+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.552 seconds
[2023-12-05T21:56:12.161+0100] {processor.py:157} INFO - Started process (PID=10) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:56:12.170+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:56:12.177+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:56:12.174+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:56:13.646+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:56:13.645+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:56:14.794+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:56:14.786+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:56:14.818+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:56:15.786+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:56:15.785+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:56:15.944+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:56:15.943+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:56:16.070+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.970 seconds
[2023-12-05T21:56:46.964+0100] {processor.py:157} INFO - Started process (PID=61) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:56:46.973+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:56:46.979+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:56:46.976+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:56:48.540+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:56:48.540+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:56:49.808+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:56:49.796+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:56:49.846+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:56:50.205+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:56:50.203+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:56:50.393+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:56:50.392+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:56:50.509+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.583 seconds
[2023-12-05T21:57:20.975+0100] {processor.py:157} INFO - Started process (PID=115) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:57:20.989+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:57:20.999+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:57:20.997+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:57:23.379+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:57:23.374+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:57:26.086+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:57:26.078+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:57:26.115+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:57:27.680+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:57:27.679+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:57:27.929+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:57:27.928+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:57:28.157+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 7.232 seconds
[2023-12-05T21:57:58.834+0100] {processor.py:157} INFO - Started process (PID=158) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:57:58.856+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:57:58.872+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:57:58.862+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:58:01.328+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:58:01.326+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:58:03.869+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:58:03.853+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:58:03.915+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:58:04.670+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:58:04.668+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:58:05.165+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:58:05.164+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:58:06.432+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 7.712 seconds
[2023-12-05T21:58:38.029+0100] {processor.py:157} INFO - Started process (PID=217) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:58:38.038+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:58:38.045+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:58:38.042+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:58:39.676+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:58:39.675+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:58:40.943+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:58:40.933+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:58:40.970+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:58:42.033+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:58:42.032+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:58:42.183+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:58:42.182+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:58:42.305+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.314 seconds
[2023-12-05T21:59:13.057+0100] {processor.py:157} INFO - Started process (PID=273) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:59:13.065+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:59:13.072+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:59:13.070+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:59:14.527+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:59:14.526+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:59:15.753+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:59:15.742+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:59:15.778+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:59:16.076+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:59:16.075+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:59:16.258+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:59:16.258+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:59:16.372+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.353 seconds
[2023-12-05T21:59:47.465+0100] {processor.py:157} INFO - Started process (PID=329) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:59:47.474+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T21:59:47.480+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:59:47.478+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:59:49.024+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:59:49.024+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T21:59:50.241+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:59:50.232+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T21:59:50.266+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T21:59:51.256+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:59:51.255+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T21:59:51.412+0100] {logging_mixin.py:154} INFO - [2023-12-05T21:59:51.411+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T21:59:51.528+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.100 seconds
[2023-12-05T22:00:22.465+0100] {processor.py:157} INFO - Started process (PID=395) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:00:22.474+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:00:22.481+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:00:22.479+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:00:23.967+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:00:23.966+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:00:25.130+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:00:25.122+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:00:25.154+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:00:25.446+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:00:25.445+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:00:25.630+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:00:25.629+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:00:25.744+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.316 seconds
[2023-12-05T22:00:56.231+0100] {processor.py:157} INFO - Started process (PID=448) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:00:56.239+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:00:56.246+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:00:56.243+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:00:57.685+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:00:57.684+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:00:58.872+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:00:58.863+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:00:58.897+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:00:59.847+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:00:59.846+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:00:59.997+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:00:59.996+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:01:00.137+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.942 seconds
[2023-12-05T22:01:30.749+0100] {processor.py:157} INFO - Started process (PID=499) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:01:30.761+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:01:30.766+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:01:30.764+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:01:32.258+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:01:32.257+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:01:33.411+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:01:33.399+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:01:33.436+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:01:33.722+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:01:33.721+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:01:33.902+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:01:33.901+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:01:34.009+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.301 seconds
[2023-12-05T22:02:04.367+0100] {processor.py:157} INFO - Started process (PID=554) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:02:04.376+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:02:04.381+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:02:04.379+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:02:05.871+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:02:05.870+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:02:07.118+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:02:07.108+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:02:07.143+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:02:08.108+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:02:08.107+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:02:08.266+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:02:08.265+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:02:08.382+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.053 seconds
[2023-12-05T22:02:38.665+0100] {processor.py:157} INFO - Started process (PID=605) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:02:38.681+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:02:38.690+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:02:38.687+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:02:40.240+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:02:40.239+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:02:41.364+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:02:41.355+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:02:41.388+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:02:41.689+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:02:41.688+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:02:41.865+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:02:41.865+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:02:41.975+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.367 seconds
[2023-12-05T22:03:12.275+0100] {processor.py:157} INFO - Started process (PID=656) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:03:12.285+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:03:12.291+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:03:12.288+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:03:13.837+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:03:13.836+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:03:14.989+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:03:14.980+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:03:15.014+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:03:16.076+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:03:16.075+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:03:16.238+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:03:16.237+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:03:16.355+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.118 seconds
[2023-12-05T22:03:46.620+0100] {processor.py:157} INFO - Started process (PID=699) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:03:46.634+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:03:46.641+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:03:46.639+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:03:48.614+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:03:48.614+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:03:50.334+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:03:50.322+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:03:50.369+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:03:50.770+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:03:50.769+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:03:51.000+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:03:50.999+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:03:51.137+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.571 seconds
[2023-12-05T22:04:21.723+0100] {processor.py:157} INFO - Started process (PID=750) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:04:21.732+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:04:21.738+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:04:21.736+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:04:23.560+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:04:23.559+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:04:25.195+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:04:25.181+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:04:25.232+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:04:26.340+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:04:26.339+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:04:26.539+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:04:26.538+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:04:26.679+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 5.015 seconds
[2023-12-05T22:04:57.437+0100] {processor.py:157} INFO - Started process (PID=809) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:04:57.446+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:04:57.452+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:04:57.450+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:04:58.982+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:04:58.982+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:05:00.213+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:05:00.203+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:05:00.239+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:05:00.552+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:05:00.551+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:05:00.734+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:05:00.733+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:05:00.845+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.446 seconds
[2023-12-05T22:05:32.413+0100] {processor.py:157} INFO - Started process (PID=865) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:05:32.426+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:05:32.433+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:05:32.431+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:05:33.967+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:05:33.966+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:05:35.092+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:05:35.083+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:05:35.116+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:05:36.112+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:05:36.111+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:05:36.273+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:05:36.273+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:05:36.390+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.018 seconds
[2023-12-05T22:06:08.366+0100] {processor.py:157} INFO - Started process (PID=921) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:06:08.375+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:06:08.381+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:06:08.379+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:06:09.944+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:06:09.944+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:06:11.183+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:06:11.175+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:06:11.208+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:06:11.513+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:06:11.512+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:06:11.699+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:06:11.698+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:06:11.810+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.485 seconds
[2023-12-05T22:06:43.702+0100] {processor.py:157} INFO - Started process (PID=982) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:06:43.710+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:06:43.716+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:06:43.714+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:06:46.001+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:06:46.000+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:06:47.998+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:06:47.977+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:06:48.040+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:06:49.358+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:06:49.357+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:06:49.567+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:06:49.566+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:06:49.748+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 6.085 seconds
[2023-12-05T22:07:20.223+0100] {processor.py:157} INFO - Started process (PID=1038) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:07:20.236+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:07:20.244+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:07:20.242+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:07:21.919+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:07:21.919+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:07:23.337+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:07:23.326+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:07:23.371+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:07:23.729+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:07:23.728+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:07:24.000+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:07:23.999+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:07:24.136+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.973 seconds
[2023-12-05T22:07:54.979+0100] {processor.py:157} INFO - Started process (PID=1091) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:07:54.991+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:07:54.999+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:07:54.996+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:07:56.979+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:07:56.978+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:07:58.250+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:07:58.241+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:07:58.277+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:07:59.470+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:07:59.469+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:07:59.635+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:07:59.634+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:07:59.767+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.845 seconds
[2023-12-05T22:08:30.030+0100] {processor.py:157} INFO - Started process (PID=1142) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:08:30.039+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:08:30.045+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:08:30.042+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:08:31.604+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:08:31.603+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:08:32.793+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:08:32.783+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:08:32.820+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:08:33.217+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:08:33.217+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:08:33.399+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:08:33.398+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:08:33.514+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.521 seconds
[2023-12-05T22:09:03.882+0100] {processor.py:157} INFO - Started process (PID=1191) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:09:03.897+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:09:03.905+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:09:03.901+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:09:05.569+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:09:05.568+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:09:06.798+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:09:06.789+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:09:06.823+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:09:07.143+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:09:07.142+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:09:07.323+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:09:07.322+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:09:07.436+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.633 seconds
[2023-12-05T22:09:38.177+0100] {processor.py:157} INFO - Started process (PID=1242) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:09:38.186+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:09:38.193+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:09:38.190+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:09:39.746+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:09:39.745+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:09:41.057+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:09:41.048+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:09:41.083+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:09:42.328+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:09:42.327+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:09:42.499+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:09:42.499+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:09:42.616+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.480 seconds
[2023-12-05T22:10:13.700+0100] {processor.py:157} INFO - Started process (PID=1295) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:10:13.709+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:10:13.715+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:10:13.713+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:10:15.301+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:10:15.300+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:10:16.480+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:10:16.471+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:10:16.505+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:10:16.897+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:10:16.896+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:10:17.095+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:10:17.094+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:10:17.203+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.542 seconds
[2023-12-05T22:10:47.877+0100] {processor.py:157} INFO - Started process (PID=1357) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:10:47.885+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:10:47.891+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:10:47.889+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:10:49.395+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:10:49.395+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:10:50.521+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:10:50.512+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:10:50.546+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:10:51.489+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:10:51.489+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:10:51.642+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:10:51.641+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:10:51.759+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.919 seconds
[2023-12-05T22:11:22.567+0100] {processor.py:157} INFO - Started process (PID=1408) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:11:22.580+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:11:22.590+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:11:22.586+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:11:24.104+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:11:24.103+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:11:25.330+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:11:25.321+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:11:25.356+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:11:25.738+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:11:25.737+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:11:25.943+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:11:25.942+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:11:26.067+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.537 seconds
[2023-12-05T22:11:56.901+0100] {processor.py:157} INFO - Started process (PID=1462) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:11:56.911+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:11:56.917+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:11:56.915+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:11:58.473+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:11:58.472+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:11:59.708+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:11:59.698+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:11:59.734+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:12:00.053+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:12:00.052+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:12:00.233+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:12:00.232+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:12:00.354+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.494 seconds
[2023-12-05T22:12:30.843+0100] {processor.py:157} INFO - Started process (PID=1523) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:12:30.852+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:12:30.858+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:12:30.856+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:12:32.407+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:12:32.406+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:12:33.636+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:12:33.628+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:12:33.661+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:12:34.666+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:12:34.665+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:12:34.838+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:12:34.837+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:12:34.956+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.155 seconds
[2023-12-05T22:13:05.226+0100] {processor.py:157} INFO - Started process (PID=1581) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:13:05.235+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:13:05.242+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:13:05.239+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:13:06.983+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:13:06.982+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:13:08.178+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:13:08.170+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:13:08.203+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:13:08.564+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:13:08.564+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:13:08.741+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:13:08.741+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:13:08.849+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.661 seconds
[2023-12-05T22:13:39.920+0100] {processor.py:157} INFO - Started process (PID=1637) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:13:39.929+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:13:39.934+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:13:39.932+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:13:41.439+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:13:41.438+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:13:42.573+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:13:42.564+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:13:42.600+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:13:42.895+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:13:42.894+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:13:43.074+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:13:43.073+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:13:43.182+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.300 seconds
[2023-12-05T22:14:13.433+0100] {processor.py:157} INFO - Started process (PID=1688) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:14:13.442+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:14:13.448+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:14:13.446+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:14:14.952+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:14:14.951+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:14:16.083+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:14:16.074+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:14:16.108+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:14:17.075+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:14:17.074+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:14:17.233+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:14:17.232+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:14:17.358+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.961 seconds
[2023-12-05T22:14:47.839+0100] {processor.py:157} INFO - Started process (PID=1739) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:14:47.848+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:14:47.854+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:14:47.851+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:14:49.335+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:14:49.334+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:14:50.445+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:14:50.436+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:14:50.470+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:14:50.751+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:14:50.750+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:14:50.934+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:14:50.933+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:14:51.047+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.251 seconds
[2023-12-05T22:15:21.910+0100] {processor.py:157} INFO - Started process (PID=1790) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:15:21.919+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:15:21.925+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:15:21.922+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:15:23.588+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:15:23.587+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:15:25.052+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:15:25.041+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:15:25.082+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:15:26.108+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:15:26.107+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:15:26.281+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:15:26.280+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:15:26.428+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.558 seconds
[2023-12-05T22:15:56.659+0100] {processor.py:157} INFO - Started process (PID=1841) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:15:56.668+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:15:56.674+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:15:56.672+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:15:58.166+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:15:58.166+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:15:59.307+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:15:59.296+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:15:59.333+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:15:59.688+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:15:59.688+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:15:59.857+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:15:59.856+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:15:59.964+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.346 seconds
[2023-12-05T22:16:30.576+0100] {processor.py:157} INFO - Started process (PID=1892) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:16:30.585+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:16:30.592+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:16:30.590+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:16:32.083+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:16:32.082+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:16:33.215+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:16:33.206+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:16:33.242+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:16:33.543+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:16:33.542+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:16:33.733+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:16:33.732+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:16:33.843+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.306 seconds
[2023-12-05T22:17:04.225+0100] {processor.py:157} INFO - Started process (PID=1943) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:17:04.234+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:17:04.240+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:17:04.237+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:17:05.807+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:17:05.806+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:17:06.985+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:17:06.975+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:17:07.010+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:17:07.998+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:17:07.997+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:17:08.153+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:17:08.152+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:17:08.275+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.087 seconds
[2023-12-05T22:17:38.770+0100] {processor.py:157} INFO - Started process (PID=1994) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:17:38.778+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:17:38.784+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:17:38.782+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:17:40.251+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:17:40.250+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:17:41.369+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:17:41.360+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:17:41.396+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:17:41.775+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:17:41.774+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:17:41.953+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:17:41.952+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:17:42.060+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.327 seconds
[2023-12-05T22:18:12.770+0100] {processor.py:157} INFO - Started process (PID=2043) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:18:12.780+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:18:12.786+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:18:12.784+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:18:14.351+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:18:14.350+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:18:16.015+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:18:16.002+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:18:16.051+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:18:16.378+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:18:16.376+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:18:16.682+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:18:16.681+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:18:16.822+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.096 seconds
[2023-12-05T22:18:47.396+0100] {processor.py:157} INFO - Started process (PID=2099) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:18:47.405+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:18:47.410+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:18:47.408+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:18:49.007+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:18:49.006+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:18:50.238+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:18:50.229+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:18:50.263+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:18:51.222+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:18:51.221+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:18:51.387+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:18:51.386+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:18:51.516+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.158 seconds
[2023-12-05T22:19:21.953+0100] {processor.py:157} INFO - Started process (PID=2162) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:19:21.962+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:19:21.970+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:19:21.968+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:19:23.528+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:19:23.528+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:19:24.856+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:19:24.848+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:19:24.884+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:19:25.250+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:19:25.249+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:19:25.424+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:19:25.423+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:19:25.528+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.616 seconds
[2023-12-05T22:19:56.043+0100] {processor.py:157} INFO - Started process (PID=2221) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:19:56.053+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:19:56.059+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:19:56.057+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:19:57.549+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:19:57.548+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:19:58.716+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:19:58.704+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:19:58.740+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:19:59.035+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:19:59.034+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:19:59.208+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:19:59.207+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:19:59.314+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.307 seconds
[2023-12-05T22:20:29.798+0100] {processor.py:157} INFO - Started process (PID=2274) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:20:29.807+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:20:29.812+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:20:29.810+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:20:31.346+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:20:31.346+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:20:32.484+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:20:32.475+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:20:32.511+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:20:33.482+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:20:33.481+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:20:33.643+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:20:33.642+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:20:33.765+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.004 seconds
[2023-12-05T22:21:03.988+0100] {processor.py:157} INFO - Started process (PID=2323) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:21:03.998+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:21:04.006+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:21:04.002+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:21:05.537+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:21:05.536+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:21:06.697+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:21:06.689+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:21:06.722+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:21:07.009+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:21:07.008+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:21:07.191+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:21:07.190+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:21:07.313+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.372 seconds
[2023-12-05T22:21:37.832+0100] {processor.py:157} INFO - Started process (PID=2374) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:21:37.841+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:21:37.847+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:21:37.845+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:21:39.401+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:21:39.400+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:21:40.576+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:21:40.566+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:21:40.603+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:21:41.629+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:21:41.628+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:21:41.784+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:21:41.783+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:21:41.907+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.112 seconds
[2023-12-05T22:22:12.175+0100] {processor.py:157} INFO - Started process (PID=2425) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:22:12.190+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:22:12.198+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:22:12.195+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:22:13.782+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:22:13.781+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:22:14.953+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:22:14.941+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:22:14.978+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:22:15.277+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:22:15.277+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:22:15.458+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:22:15.457+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:22:15.565+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.435 seconds
[2023-12-05T22:22:45.796+0100] {processor.py:157} INFO - Started process (PID=2476) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:22:45.805+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:22:45.811+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:22:45.809+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:22:47.410+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:22:47.409+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:22:48.525+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:22:48.517+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:22:48.550+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:22:49.515+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:22:49.514+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:22:49.675+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:22:49.674+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:22:49.787+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.031 seconds
[2023-12-05T22:23:20.028+0100] {processor.py:157} INFO - Started process (PID=2527) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:23:20.037+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:23:20.043+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:23:20.041+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:23:21.711+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:23:21.710+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:23:22.909+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:23:22.901+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:23:22.934+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:23:23.219+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:23:23.218+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:23:23.402+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:23:23.400+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:23:23.525+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.534 seconds
[2023-12-05T22:23:54.156+0100] {processor.py:157} INFO - Started process (PID=2570) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:23:54.166+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:23:54.172+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:23:54.170+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:23:55.895+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:23:55.894+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:23:57.292+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:23:57.283+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:23:57.318+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:23:58.310+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:23:58.309+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:23:58.460+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:23:58.459+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:23:58.574+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.460 seconds
[2023-12-05T22:24:28.991+0100] {processor.py:157} INFO - Started process (PID=2629) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:24:29.001+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:24:29.006+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:24:29.004+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:24:30.538+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:24:30.537+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:24:31.709+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:24:31.698+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:24:31.741+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:24:32.118+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:24:32.117+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:24:32.310+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:24:32.309+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:24:32.420+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.468 seconds
[2023-12-05T22:25:02.638+0100] {processor.py:157} INFO - Started process (PID=2672) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:25:02.648+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:25:02.654+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:25:02.652+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:25:04.327+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:25:04.327+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:25:05.535+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:25:05.527+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:25:05.560+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:25:06.518+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:25:06.517+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:25:06.692+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:25:06.691+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:25:06.818+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 4.219 seconds
[2023-12-05T22:25:38.859+0100] {processor.py:157} INFO - Started process (PID=2736) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:25:38.868+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:25:38.876+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:25:38.874+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:25:40.508+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:25:40.507+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:25:41.695+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:25:41.686+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:25:41.720+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:25:42.033+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:25:42.032+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:25:42.240+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:25:42.239+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:25:42.347+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 3.534 seconds
[2023-12-05T22:26:14.747+0100] {processor.py:157} INFO - Started process (PID=2792) to work on /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:26:14.765+0100] {processor.py:829} INFO - Processing file /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py for tasks to queue
[2023-12-05T22:26:14.780+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:26:14.773+0100] {dagbag.py:536} INFO - Filling up the DagBag from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:26:17.800+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:26:17.799+0100] {utils.py:160} INFO - NumExpr defaulting to 8 threads.
[2023-12-05T22:26:20.219+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:26:20.201+0100] {templater.py:76} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/root/miniconda3/envs/airflow-venv/lib/python3.9/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: python /mnt/d/local-repo-github/enr_portfolio_modeling/src/data/etl_xlsx_mssql/hedge_scd2.sql
[2023-12-05T22:26:20.270+0100] {processor.py:839} INFO - DAG(s) dict_keys(['pipeline_mssql']) retrieved from /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py
[2023-12-05T22:26:22.236+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:26:22.234+0100] {dag.py:2941} INFO - Sync 1 DAGs
[2023-12-05T22:26:22.519+0100] {logging_mixin.py:154} INFO - [2023-12-05T22:26:22.518+0100] {dag.py:3722} INFO - Setting next_dagrun for pipeline_mssql to 2023-12-06T21:00:00+00:00, run_after=2023-12-07T21:00:00+00:00
[2023-12-05T22:26:22.725+0100] {processor.py:179} INFO - Processing /mnt/d/local-repo-github/enr_portfolio_modeling/pipelines/dags/pipeline_etl_mssql.py took 8.052 seconds
